In [2]:
import numpy as np
# Create a rank 1 array
a = np.array([0, 1, 2])
print(type(a))
# this will print the dimension of the array
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
# Change an element of the array
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [3]:
# Create a rank 2 array
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [30]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
c = np.full((3,3), 100)
print(c)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [13]:
d = np.random.random((3,3))
print(d)

[[0.50518853 0.93473231 0.00686922]
 [0.23097506 0.66649767 0.91635925]
 [0.28737401 0.88556429 0.13358901]]


In [14]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
f = np.array([2, 3, 1, 0])
print(f)

[2 3 1 0]


In [19]:
g = np.arange(20)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [21]:
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [25]:
# linspace() will create arrays with a specified number of items which are
# spaced equally between the specified beginning and end values j= np.linspace(start, stop, num)
j = np.linspace(2, 4, 5)
print(j)

[2.  2.5 3.  3.5 4. ]


In [29]:
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [32]:
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


In [34]:
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [35]:
import numpy as np
a = np.array([1, 2, 5, 3])
# add 1 to every element
print ("Adding 1 to every element:", a+1)
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
# square each element
print ("Squaring each element:", a**2)
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [43]:
data=np.loadtxt('fitness.txt',dtype="str")
print(data)

[['06-10-2017' '5464' '200' '181' '5' '0' '66']
 ['07-10-2017' '6041' '100' '197' '8' '0' '66']
 ['08-10-2017' '25' '100' '0' '5' '0' '66']
 ['09-10-2017' '5461' '100' '174' '4' '0' '66']
 ['10-10-2017' '6915' '200' '223' '5' '500' '66']
 ['11-10-2017' '4545' '100' '149' '6' '0' '66']
 ['12-10-2017' '4340' '100' '140' '6' '0' '66']
 ['13-10-2017' '1230' '100' '38' '7' '0' '66']
 ['14-10-2017' '61' '100' '1' '5' '0' '66']
 ['15-10-2017' '1258' '100' '40' '6' '0' '65']
 ['16-10-2017' '3148' '100' '101' '8' '0' '65']
 ['17-10-2017' '4687' '100' '152' '5' '0' '65']
 ['18-10-2017' '4732' '300' '150' '6' '500' '65']
 ['19-10-2017' '3519' '100' '113' '7' '0' '65']
 ['20-10-2017' '1580' '100' '49' '5' '0' '65']
 ['21-10-2017' '2822' '100' '86' '6' '0' '65']
 ['22-10-2017' '181' '100' '6' '8' '0' '65']
 ['23-10-2017' '3158' '200' '99' '5' '0' '65']
 ['24-10-2017' '4383' '200' '143' '4' '0' '64']
 ['25-10-2017' '3881' '200' '125' '5' '0' '64']
 ['26-10-2017' '4037' '200' '129' '6' '0' '64']
 ['2

/tmp/ipython-input-972727082.py:1: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data=np.loadtxt('fitness.txt',dtype="str")
